//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int id_admin { get; set; }
        public string email { get; set; }
        public string matkhau { get; set; }
        public string ten { get; set; }
        public string sodienthoai { get; set; }
    }
}
