//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdonhang
    {
        public string id_donhang { get; set; }
        public string id_sanpham { get; set; }
        public decimal dongia { get; set; }
        public int soluong { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
