//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieunhap
    {
        public int id_phieunhap { get; set; }
        public string id_sanpham { get; set; }
        public int soluongsp { get; set; }
        public decimal gianhap { get; set; }
        public System.DateTime ngaynhap { get; set; }
    
        public virtual sanpham sanpham { get; set; }
    }
}
