//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieugiaohang
    {
        public int id_pgh { get; set; }
        public System.DateTime ngaygiaohang { get; set; }
        public string diachi { get; set; }
        public string tenkhachhang { get; set; }
        public string sodienthoai { get; set; }
        public string id_donhang { get; set; }
        public string ghichu { get; set; }
        public decimal phigiaohang { get; set; }
    
        public virtual donhang donhang { get; set; }
    }
}
